import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { safeURL, normaliseProject, parseCSV, parseEventTime, midnightVienna, normaliseEvents, selectEvents, eventState, eventTimeLabel, fetchText } from '../js/core.mjs';
import { resolveEventFeed } from '../scripts/build.mjs';
const base='https://example.org/Project/portal/metadata.json';
const project={version:1,title:'A project',project:'../',preview:'./preview.svg',embed:'./index.html'};
const event={id:'one',title:'Opening',start:'2026-06-09T10:00:00+02:00',end:'2026-06-09T16:30:00+02:00'};

test('URLs resolve beside the metadata, not beside the central portal',()=>{const p=normaliseProject(project,base);assert.equal(p.preview,'https://example.org/Project/portal/preview.svg');assert.equal(p.embed,'https://example.org/Project/portal/index.html');assert.equal(p.project,'https://example.org/Project/');});
test('legacy subtitle and portal fields work',()=>{const p=normaliseProject({title:'A',subtitle:'B',portal:'./',repository:'../'},base);assert.equal(p.description,'B');assert.equal(p.embed,'https://example.org/Project/portal/');});
test('reject javascript/data/file URLs, credentials and remote HTTP',()=>{for(const x of ['javascript:alert(1)','data:text/html,test','file:///etc/passwd','https://user:pass@example.org','http://example.org/'])assert.equal(safeURL(x,base),null);});
test('local development works under a repository subpath',()=>assert.equal(safeURL('../assets/image.svg','http://127.0.0.1:8000/PORTAL/data/projects.json'),'http://127.0.0.1:8000/PORTAL/assets/image.svg'));
test('missing required project fields fail safely',()=>{assert.throws(()=>normaliseProject({},base));assert.throws(()=>normaliseProject({title:'A',project:'javascript:alert(1)'},base));});
test('unknown contract versions fail safely',()=>assert.throws(()=>normaliseProject({...project,version:2},base)));
test('metadata stays plain text, with bounds on fields',()=>{const p=normaliseProject({...project,title:'<img onerror=alert(1)>',tags:Array(20).fill('x')},base);assert.equal(p.title,'<img onerror=alert(1)>');assert.equal(p.tags.length,8);});
test('invalid optional embed URLs are not exposed',()=>assert.equal(normaliseProject({...project,embed:'javascript:alert(1)'},base).embed,null));
test('CSV handles quotes, commas, BOM, CRLF and multiline cells',()=>{const rows=parseCSV('\uFEFFtitle,start,description\r\n"A, B",2026-09-09,"line 1\nline ""2"""\r\n');assert.deepEqual(rows,[{title:'A, B',start:'2026-09-09',description:'line 1\nline "2"'}]);});
test('CSV empty feed with valid headers is valid',()=>assert.deepEqual(parseCSV('title,start\n'),[]));
test('CSV blank rows ignored',()=>assert.equal(parseCSV('title,start\n\nA,2026-09-09\n\n').length,1));
test('CSV invalid quotes rejected',()=>{assert.throws(()=>parseCSV('title,start\n"A,2026-09-09'));assert.throws(()=>parseCSV('title,start\n"A"oops,2026-09-09'));});
test('CSV invalid headers and extra columns rejected',()=>{for(const s of ['title,title\nA,B','name,date\nA,B','title,start\nA,B,C'])assert.throws(()=>parseCSV(s));});
test('ISO timestamps use their explicit offset',()=>assert.equal(parseEventTime(event.start).instant,Date.parse('2026-06-09T08:00:00Z')));
test('invalid dates and naive local times rejected',()=>{for(const s of ['2026-02-30','2026-06-09T10:00','2026-02-30T10:00:00Z','2026-06-09T25:00:00Z','tomorrow'])assert.throws(()=>parseEventTime(s));});
test('Vienna midnight uses summer and winter offsets',()=>{assert.equal(new Date(midnightVienna('2026-06-09')).toISOString(),'2026-06-08T22:00:00.000Z');assert.equal(new Date(midnightVienna('2026-01-09')).toISOString(),'2026-01-08T23:00:00.000Z');});
test('all-day event handles the 23-hour spring DST day',()=>{const [e]=normaliseEvents([{title:'Spring',start:'2026-03-29'}],base);assert.equal(e.end-e.start,23*3600000);});
test('all-day event handles the 25-hour autumn DST day',()=>{const [e]=normaliseEvents([{title:'Autumn',start:'2026-10-25'}],base);assert.equal(e.end-e.start,25*3600000);});
test('all-day end dates are exclusive',()=>{const [e]=normaliseEvents([{title:'Festival',start:'2026-06-09',end:'2026-06-11'}],base);assert.equal(e.end-e.start,48*3600000);});
test('ongoing events stay upcoming until their end',()=>{const [e]=normaliseEvents([event],base);assert.equal(eventState(e,e.start-1),'upcoming');assert.equal(eventState(e,e.start),'ongoing');assert.equal(selectEvents([e],'upcoming',e.end-1).length,1);assert.equal(eventState(e,e.end),'past');});
test('timed event without end moves to archive after start',()=>{const [e]=normaliseEvents([{title:'A',start:event.start}],base);assert.equal(e.end-e.start,1);});
test('end before start and mixed date types fail',()=>{assert.throws(()=>normaliseEvents([{...event,end:'2026-06-08T10:00:00Z'}],base));assert.throws(()=>normaliseEvents([{...event,end:'2026-06-10'}],base));});
test('duplicate event ids fail',()=>assert.throws(()=>normaliseEvents([event,event],base)));
test('unpublished rows are excluded',()=>assert.equal(normaliseEvents([{...event,published:false},{...event,published:'false'}],base).length,0));
test('event links resolve against the feed URL',()=>assert.equal(normaliseEvents([{...event,url:'./info'}],base)[0].url,'https://example.org/Project/portal/info'));
test('event labels always use Vienna time',()=>assert.equal(eventTimeLabel(normaliseEvents([event],base)[0]),'10:00–16:30'));
test('archive sorts most recent first',()=>{const e=normaliseEvents([event,{...event,id:'two',start:'2026-07-01T10:00:00+02:00',end:'2026-07-01T12:00:00+02:00'}],base);assert.equal(selectEvents(e,'past',Date.parse('2026-09-09'))[0].id,'two');});
test('no configured feed uses local saved events',async()=>{const p=await resolveEventFeed({}, {events:[event]});assert.equal(p.feed.state,'local');});
test('external CSV is mirrored, relative links rebased',async()=>{const p=await resolveEventFeed({eventsFeed:{url:'https://example.org/feed/events.csv',format:'csv'}},{events:[event]},async()=>`title,start,url\nTest,2026-09-09,./details\n`);assert.equal(p.feed.state,'external');assert.equal(p.events[0].url,'https://example.org/feed/details');});
test('external JSON is mirrored',async()=>{const p=await resolveEventFeed({eventsFeed:{url:'https://example.org/events.json',format:'json'}},{events:[]},async()=>JSON.stringify({events:[event]}));assert.equal(p.events[0].title,'Opening');assert.equal(p.feed.state,'external');});
test('external feed failures retain local listings with a visible fallback flag',async()=>{const p=await resolveEventFeed({eventsFeed:{url:'https://example.org/feed',format:'csv'}},{events:[event]},async()=>{throw new Error('offline');});assert.equal(p.feed.state,'fallback');assert.equal(p.events.length,1);});
test('malformed external dates do not erase local events',async()=>{const p=await resolveEventFeed({eventsFeed:{url:'https://example.org/feed',format:'csv'}},{events:[event]},async()=>`title,start\nBroken,not-a-date`);assert.equal(p.feed.state,'fallback');});
test('a deliberately empty external calendar stays empty',async()=>{const p=await resolveEventFeed({eventsFeed:{url:'https://example.org/feed',format:'csv'}},{events:[event]},async()=>`title,start\n`);assert.equal(p.feed.state,'external');assert.equal(p.events.length,0);});
test('registry contains four project-owned manifests with Klavier fourth and no duplicated descriptions',async()=>{const registry=JSON.parse(await readFile(new URL('../data/projects.json',import.meta.url)));assert.deepEqual(registry.projects.map(e=>e.id),['pianorules','tutor','tesserakt','klavier']);assert.equal(registry.projects[3].manifest,'https://muk-research.github.io/Klavier/portal/metadata.json');for(const e of registry.projects){assert.ok(safeURL(e.manifest));assert.equal(e.fallback,undefined);}const data=JSON.parse(await readFile(new URL('../data/events.json',import.meta.url)));assert.equal(normaliseEvents(data,base).length,1);});
test('fetchText refuses an oversized response',async()=>{const saved=globalThis.fetch;globalThis.fetch=async()=>new Response('too much',{headers:{'Content-Length':'500'}});try{await assert.rejects(fetchText('https://example.org',{maxBytes:10}),/too large/);}finally{globalThis.fetch=saved;}});
test('fetchText bounds streamed responses without content-length',async()=>{const saved=globalThis.fetch;globalThis.fetch=async()=>new Response('too much');try{await assert.rejects(fetchText('https://example.org',{maxBytes:3}),/too large/);}finally{globalThis.fetch=saved;}});
